{
    'name': 'Email CRM Lead generation',
    'version': '18.0.0.0.1',
    'category': 'Connector',
    'author': 'Sudarsanan P.R',
    'website': '',
    'summary': 'Connect Email and create leads when a new Booking has come',
    'description': """Email CRM integration""",
    'depends': ['base','web', 'contacts', 'crm', 'stock', 'sale', 'mail', 'account','sale_crm', 'purchase', 'sale_management', 'l10n_in'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'report/daily_statement_report.xml',
        'views/report_invoice_document.xml',
        'views/fetch_mail.xml',
        'views/account_move.xml',
        'views/crm_lead_inherit.xml',
        'wizard/create_invoice_wizard.xml',
        'views/menu.xml',
        'views/stock_location.xml',
        'data/ir_cron.xml',
        'views/res_config_settings.xml',  
    ],

    'license': 'OPL-1',
    'application': False,
    'auto_install': False,
    'installable': True,
}
